---
title: "STAT project"
output: pdf_document
---

```{r, echo=TRUE,warning=FALSE,message=FALSE}
library(tidyverse)
library(eeptools)
library(rvest)
##Scrape  data from online
alz=read_csv("C:/Users/endkg/Desktop/oasis_longitudinal.csv")
urls=read_html("https://www.ssa.gov/oact/STATS/table4c6.html")
tablelifeexp=urls %>% html_table(fill=TRUE)
exp=tablelifeexp %>% as.data.frame() 
exptable=exp[-1,] %>% rename(age=Exact.age,male_lifeexp=Male.2,female_lifeexp=Female.2) %>% select(age,male_lifeexp,female_lifeexp) %>% as.tibble() %>% mutate_if(is.character,as.double)
alz_lifeexp=alz %>% left_join(exptable,by=c("Age"="age")) %>% rename(sex=`M/F`)
alz_lifeexp=alz_lifeexp %>% mutate_at(c("Hand","Group","sex"),as.factor)
missna=drop_na(alz_lifeexp)
meanSES=round(mean(missna$SES))
meanMMSE=round(mean(missna$MMSE))
alz_lifeexp=alz_lifeexp %>% mutate_at("SES",~replace_na(.,meanSES))
alz_lifeexp=alz_lifeexp %>% mutate_at("MMSE",~replace_na(.,meanMMSE))
## Data Exploration
library(PerformanceAnalytics)
alz_lifeexp %>% select(Age,sex) %>% ggplot(aes(Age,fill=sex))+geom_histogram()+facet_wrap(~sex)## Age by sex graph

chart.Correlation(select(alz_lifeexp,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF),
                  histogram = TRUE,main="correlation") ##all variable correlation 
alz_lifeexp %>% select(eTIV,ASF) %>% ggplot(aes(x=eTIV,y=ASF))+geom_point(color="red")+
geom_smooth() ## significant negative correlation between ASF and eTIV. 

alz_lifeexp %>% select(CDR,EDUC,sex) %>% ggplot(aes(x=CDR,y=EDUC,fill=sex))+
  geom_boxplot() ##degree CDR by education 

alz_lifeexp %>% select(Group,sex,CDR) %>% ggplot(aes(x=Group,fill=as.factor(CDR),
                                                       color=sex))+
  geom_bar()## count group by CDR and sex


library(tidymodels)
library(modelr)
library(recipes)
alzsplit=alz_lifeexp %>% initial_split(prop = 0.8)
alztrain=alzsplit %>% training()
alztest=alzsplit %>% testing()
alzdata=recipe(CDR~sex+Age+SES+EDUC+MMSE+eTIV+nWBV,data=alztrain)
alzdata=alzdata %>% step_impute_mean(SES)
alzdata=alzdata %>% step_impute_mean(MMSE)
alzdata=alzdata %>% step_dummy(all_nominal_predictors())
alzdata=alzdata %>% step_scale(all_nominal_predictors())
##lasso
library(glmnet)
set.seed(1)
recipeworkflow=workflow()
alzlasso=linear_reg(penalty = tune(),mixture=1) %>% set_engine("glmnet") 
lassolambda=grid_regular(penalty(),levels = 3)
lassogrid=tune_grid(recipeworkflow %>% add_recipe(alzdata) %>%  add_model(alzlasso),grid=lassolambda,resamples=bootstraps(alztrain))
lassogrid %>% collect_metrics()
lowest_rmse=lassogrid %>% select_best("rmse",maximize=FALSE)
final_lasso=finalize_workflow(recipeworkflow %>% add_recipe(alzdata) %>%
add_model(alzlasso),lowest_rmse)
lasso_alz_fit=final_lasso %>% fit(alztrain)
lasso_alz_pred=lasso_alz_fit %>% predict(alztest)
lassox2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
lassoy2=alztest$CDR
sst=sum((lassoy2-mean(lassoy2))^2)
sse=sum((lasso_alz_pred-lassoy2)^2)
rs=1-sse/sst
rs
rsq_trad(lasso_alz_pred,truth = lassoy2,estimate = as.numeric(unlist(lasso_alz_pred)))
##only 57 percent fit, maybe lasso is not a good model
set.seed(1)
lassoy=alztrain$CDR
lassox=data.matrix(alztrain[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
modelasso=glmnet(lassox,lassoy,alpha=1)
cvmodel=cv.glmnet(lassox,lassoy,alpha=1)
bestlambda=cvmodel$lambda.min
bestlambda
plot(cvmodel)
bestlasso=glmnet(lassox,lassoy,lambda=bestlambda)
coef(bestlasso)
plot(modelasso,xvar = "lambda")
lassox2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
lassoy2=alztest$CDR
lassopred=predict(modelasso,s=bestlambda,newx = lassox2 )
sstlasso=sum((lassoy2-mean(lassoy2))^2)
sselasso=sum((lassopred-lassoy2)^2)
rslasso=1-sselasso/sstlasso
rslasso## 
rsq_trad(as.tibble(lassopred),truth = lassoy2,estimate = as.numeric(lassopred))
##ridge regression
set.seed(1)
alzridge=linear_reg(penalty = tune(),mixture=0) %>% set_engine("glmnet") 
ridgelambda=grid_regular(penalty(),levels = 3)
ridgegrid=tune_grid(recipeworkflow %>% add_recipe(alzdata) %>%  add_model(alzridge),grid=ridgelambda,resamples=bootstraps(alztrain))
ridgegrid %>% collect_metrics()
lowest_rmse2=ridgegrid %>% select_best("rmse",maximize=FALSE)
final_ridge=finalize_workflow(recipeworkflow %>% add_recipe(alzdata) %>%
add_model(alzridge),lowest_rmse2)
ridge_alz_fit=final_ridge %>% fit(alztrain)
ridge_alz_pred=ridge_alz_fit %>% predict(alztest)
ridgex2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
ridgey2=alztest$CDR
sst=sum((ridgey2-mean(ridgey2))^2)
sse=sum((ridge_alz_pred-ridgey2)^2)
rsridge=1-sse/sst
rsridge
rsq_trad(ridge_alz_pred,truth = ridgey2,estimate = as.numeric(unlist(ridge_alz_pred)))

ridgey=alztrain$CDR
ridgex=data.matrix(alztrain[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
modelridge=glmnet(ridgex,ridgey,alpha=0)
cvmodel2=cv.glmnet(ridgex,ridgey,alpha=0)
bestlambda2=cvmodel2$lambda.min
bestlambda2
plot(cvmodel2)
bestridge=glmnet(lassox,lassoy,lambda=bestlambda)
coef(bestridge)
plot(modelridge,xvar = "lambda")
ridgex2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
ridgey2=alztest$CDR
ridgepred=predict(modelridge,s=bestlambda2,newx = ridgex2)
sstridge=sum((ridgey2-mean(ridgey2))^2)
sseridge=sum((ridgepred-ridgey2)^2)
rsridge=1-sseridge/sstridge
rsridge## ridge regression also only fit 45 percent, may not a good model,
##but better than lasso.
rsq_trad(as.tibble(ridgepred),truth = ridgey2,estimate = as.numeric(ridgepred))
##lm
set.seed(1)
recipeworkflow=workflow()
alzlm=linear_reg() %>% set_engine("lm") %>% set_mode("regression") 
recipeworkflowlm=recipeworkflow %>% add_model(alzlm) %>% add_recipe(alzdata)
lm_alz_fit=recipeworkflowlm %>% fit(alztrain)
lm_alz_pred=lm_alz_fit %>% predict(alztest)
lmx2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
lmy2=alztest$CDR
sstlm=sum((lmy2-mean(lmy2))^2)
sselm=sum((lm_alz_pred-lmy2)^2)
rslm=1-sselm/sstlm
rslm## lm has only fit 41 percent, which worse than lasso and ridge regression.
rsq_trad(lm_alz_pred,truth = lmy2,estimate = as.numeric(unlist(lm_alz_pred)))
##knn
library(kknn)
knnalz=nearest_neighbor() %>% set_mode("regression") %>% 
set_engine("kknn",neighbors=5)
recipeworkflowknn=recipeworkflow %>% add_model(knnalz) %>% add_recipe(alzdata)
knn_alz_fit=recipeworkflowknn %>% fit(alztrain)
knn_alz_pred=knn_alz_fit %>% predict(alztest)
knnx2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
knny2=alztest$CDR
sstknn=sum((knny2-mean(knny2))^2)
sseknn=sum((knn_alz_pred-knny2)^2)
rsknn=1-sseknn/sstknn
rsknn
rsq_trad(knn_alz_pred,truth = knny2,estimate = as.numeric(unlist(knn_alz_pred)))
## knn model fit 58-59 percent, which is the better than lasso,ridge and linear model. 

##random forest
library(ranger)
set.seed(1)
rfalz=rand_forest() %>% set_mode("regression") %>% set_engine("ranger")
recipeworkflowrf=recipeworkflow %>% add_model(rfalz) %>% add_recipe(alzdata)
rf_alz_fit=recipeworkflowrf %>% fit(alztrain)
rf_alz_pred=rf_alz_fit %>% predict(alztest)
rfx2=data.matrix(alztest[,c('sex','Age','SES','EDUC','MMSE','eTIV','nWBV')])
rfy2=alztest$CDR
sstrf=sum((rfy2-mean(rfy2))^2)
sserf=sum((rf_alz_pred-rfy2)^2)
rsrf=1-sserf/sstrf
rsrf
rsq_trad(rf_alz_pred,truth = rfy2,estimate = as.numeric(unlist(rf_alz_pred)))
##compare all model


##PCA??
library(broom)
alzpca=alzdata  %>% step_pca(all_numeric(),num_comp = 7)
alzpcaest=prep(alzpca,training = alz_lifeexp)
pcadata=bake(alzpcaest,alz_lifeexp)
a=broom::tidy(pcadata)
b=a %>% mutate(percent=round(a$sd^2/sum(a$sd^2),5)) %>% rename(PC=column)
b %>% ggplot(aes(x = PC, y = percent)) + 
  geom_segment(aes(xend = PC), yend = 0, linewidth = 4)


pca=alz_lifeexp %>% select(Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF) %>%  prcomp()
variation=round(pca$sdev^2/sum(pca$sdev^2),4)
pcs=broom::tidy(pca,matrix="pcs")
pcs %>% ggplot(aes(x=PC,y=percent))+geom_segment(aes(xend=PC),yend=0,linewidth=4)

##patient level function
patientCDRlevel=function(MRIid){
  CDR=alz_lifeexp %>% filter(`MRI ID`== MRIid) %>% select(CDR)
  if(CDR==0){
    print("the patient is normal")
  }
  if(CDR==0.5){
    print("the patient is very mild dementia")
  }
  if(CDR==1){
    print("the patient is mild dementia")
  }
  if(CDR==2){
    print("the patient is moderate dementia")}
}

library(usethis)
use_git_config(user.name="endkg",user.email="chon.iao@uconn.edu")
gitcreds::gitcreds_set()
